### ISSUE TITLE
session id static

### ISSUE THREAD

**Issue by GanadiniAkshay** [GanadiniAkshay/ApiAiRecognizer#2]
var request = this.app.textRequest(context.message.text.toLowerCase(),{sessionId: 'kjfgwsjhedfcb281908'})

this needs to dynamic instead of a static hard coded value

**Comment by GanadiniAkshay** [comment]
The bug is resolved and fixed.

**Comment by patrickml** [comment]
@GanadiniAkshay since the SessionID is now a random UUID it seems that api.ai cannot follow the conversation flow. For example, if I wanted to collect multiple fields of information

![image](https://cloud.githubusercontent.com/assets/7581369/24069265/20fee604-0b7a-11e7-9a07-61dc9b86eeb6.png)

the dialog is not continuing 

![image](https://cloud.githubusercontent.com/assets/7581369/24069269/32feb28a-0b7a-11e7-8d24-3418fe32d7e5.png)

```
{ score: 1,
  intent: 'setup',
  entities:
   [ { entity: 'What is your first name?',
       type: 'fulfillment',
       startIndex: -1,
       endIndex: -1,
       score: 1 },
     { entity: true,
       type: 'actionIncomplete',
       startIndex: -1,
       endIndex: -1,
       score: 1 } ] }
/ - session.send()
/ - session.sendBatch() sending 1 messages
ChatConnector: message received.
/ - WARN: IntentDialog - no intent handler found for Default Fallback Intent
```

**Comment by GanadiniAkshay** [comment]
Oh snap..reopening the issue. Will soon fix it.

Thanks for pointing this out

**Comment by patrickml** [comment]
@GanadiniAkshay no problem!

**Comment by erickriva** [comment]
in this case, it need the contexts to follow conversation flow, alright?

**Comment by patrickml** [comment]
@erickriva i'm pretty sure API.ai handles all of that based on sessionId

**Comment by erickriva** [comment]
@patrickml i've modified the code to get contexts and use their parameters to verify "slot filling", so i'm testing now

**Comment by awebdeveloper** [comment]
I have sent across a PR that fixes it

**Comment by GanadiniAkshay** [comment]
@awebdeveloper thanks for the PR
